apiversion: apps/v1
kind: Deployment
metadata: 
  name: kubedemoapp-deployment
spec:
  replicas: 4
  selector:
    matchLables:
      app: kubedemoapp
  template:
    metadata:
      labels:
        app: kubedemoapp
    spec:
      containers:
        - name: kubedemoapp
          image: charithasree37/sample:kubeimage
          ports:
            - containerPort: 5000




